name: dev Build Debug

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Save Keystore
      run: |
        mkdir -p app/keystore
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore/keystore.jks

    - name: Create local.properties
      run: |
        echo '${{ secrets.LOCAL_PROPERTIES }}' > local.properties
        echo "storeFile=keystore/keystore.jks" >> local.properties

    - name: Print local.properties contents
      run: cat local.properties
  
    - name: Create google-services
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' | base64 -d > app/google-services.json
  
    - name: Build debug
      run: |
        ./gradlew assembleDebug
        -PKAKAO_SDK_APPKEY="${{ secrets.KAKAO_SDK_APPKEY }}"

    - name: Upload Debug APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          testers: ${{ secrets.ALPHA_TESTER }}
          file: app/build/outputs/apk/debug/app-debug.apk
